title: 设计模式
author: PasseRR

version: 1.0
gitbook_version: 3.2.3

nav: on
baseurl: '/DesignPatterns'
# 主题cdn地址
# theme-cdn: 'https://cdn.jsdelivr.net/gh/PasseRR/jekyll-gitbook-theme'
theme-cdn: '/DesignPatterns'
# cdn: 'https://cdn.jsdelivr.net/gh/PasseRR/DesignPatterns/docs'
cdn: '/DesignPatterns'
rss: RSS
# 文章目录
collections:
  chapters:
    permalink: /:categories/:name:output_ext
    output: true

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [ 404.md, search.md ]

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:name:output_ext

exclude:
  - _drafts

destination: ./_site
incremental: false
regenerate: true

# google分析gtag
ga: G-1L1DPX3PFD
# 百度统计hm
hm: 8537fef7fc5f543ba1ad52b802978f07

remote_theme: PasseRR/jekyll-gitbook-theme

url: "https://www.xiehai.win"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
